name: "sigma-services"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: "sigma"
                uid: "1337"
        volumes:
            - .:/app
        ports:
            - "443:443"
        depends_on:
            - database

    database:
        image: mariadb
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: sigma
            MYSQL_USER: root
            MYSQL_PASSWORD: ""
        volumes:
            - .data:/var/lib/mysql
        ports:
            - "3306:3306"
