<?php

namespace App\Filament\Resources\Ddas\ArtshowPickupResource\Pages;

use App\Filament\Resources\Ddas\ArtshowPickupResource;
use Filament\Forms\Form;
use Filament\Resources\Pages\CreateRecord;

class CreateArtshowPickup extends CreateRecord
{
    protected static string $resource = ArtshowPickupResource::class;
    protected static string $view = "filament.resources.ddas.artshow-pickup";

    public function mount(): void {
        parent::mount();
    }


    public function form(Form $form): Form {
        return parent::form($form); // TODO: Change the autogenerated stub
    }
}
