<?php

namespace App\Filament\Resources\Ddas\ArtshowPickups\Pages;

use Filament\Schemas\Schema;
use App\Filament\Resources\Ddas\ArtshowPickups\ArtshowPickupResource;
use Filament\Resources\Pages\CreateRecord;

class CreateArtshowPickup extends CreateRecord
{
    protected static string $resource = ArtshowPickupResource::class;
    protected string $view = "filament.resources.ddas.artshow-pickup";

    public function mount(): void {
        parent::mount();
    }


    public function form(Schema $schema): Schema {
        return parent::form($schema); // TODO: Change the autogenerated stub
    }
}
